baseURL = "https://geoscience-lijh.github.io/Geoscience-Lijh/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "My Blog"
copyright = "2024, Jiahao Li."
theme = "diary"

#Google Analytics
[services]
  [services.googleAnalytics]
    id = "G-XXXXXXXXXX"  # Your Google Analytics ID

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = ""
enableGitalk = true
enableGiscus = false
useLastMod = true

[params.math]
  katex = true

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = "abcdefghzd"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.gitalk]
  owner = "Geoscience-Lijh"
  repo = "Geoscience-Lijh"
  client_id = "Ov23li3dRCbMuCFdJ4ln"
  client_secret = "59bfe3091cb20b3b25044d282bc7cc81d7d0111d"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="username/repo"
    data_repo_id="**************************"    
    data_category="General"
    data_category_id="*********************"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="en"
    crossorigin="anonymous"


[[menu.main]]
url = "/introduction/"
name = "Introduction"
weight = 1


[[menu.main]]
url = "/programme/"
name = "Programming"
weight = 3

[[menu.main]]
url = "/math/"
name = "Mathematics"
weight = 4

[[menu.main]]
url = "/geology/"
name = "Geology"
weight = 5

[[menu.main]]
url = "/geophysics/"
name = "Geophysics"
weight = 6

[[menu.main]]
url = "/references/"
name = "References"
weight = 7

[[menu.main]]
url = "/workshop/"
name = "Workshop"
weight = 8

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 9

[[menu.main]]
url = "/unfiled/"
name = "Unfiled"
weight = 10

